### ISSUE TITLE
Getting constructor error from Vue

### ISSUE THREAD

**Issue by dimikagi** [aws-samples/amazon-s3-presigned-urls-aws-sam#12]
When loading the index.html page, I am now getting this error in the web dev console:
Uncaught TypeError: Vue is not a constructor

Not sure what's changed but this sample no longer works for me when it was fine from January 11th (when I deployed it) to February 4th (last successful use of it). I tried backing off to Vue 3.2.29 and 3.2.28 but neither of those work, either.

**Comment by dimikagi** [comment]
I actually just changed the include to this and it now worked:
https://it.vuejs.org/js/vue.min.js

**Comment by felixabreu** [comment]
this worked for me as well! 

> I actually just changed the include to this and it now worked: https://it.vuejs.org/js/vue.min.js

**Comment by alexandrosgkesos** [comment]
Same here
